type Status {
    status: String!
}

type AddEgg {
    id: String!
}

type Mutation {
    addEggPic(eggPicId: String!, eggId: String!): Status!
    addEgg(name: String!, picIds: [String!]!): AddEgg!
    deleteEgg(eggId: ID!): Status!
    likeEgg(eggId: ID!): Status!
    unlikeEgg(eggId: ID!): Status!
}

type Egg {
    picIds: [String!]!
    name: String!
    id: String!
}

type Query {
    myEggs: [Egg!]!
    test: String!
    allEggs: [Egg!]!
    likes: [Egg!]!
}

schema {
    query: Query,
    mutation: Mutation
}
