type Status {
    status: String!
}

type Mutation {
    addEggPic(eggPicId: String!): Status!
}

type EggPic {
    id: String!
}

type Query {
    myEggPics: [EggPic!]!
}

schema {
    query: Query,
    mutation: Mutation
}
